name: Validate
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  validate:
    uses: './.github/workflows/validate.yml'
    secrets: inherit

  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: bun publish:web:docker
        working-directory: web
      - run: curl -X POST -i ${{ secrets.UPDATE_WEBSITE_WEBHOOK }}
