name: Validate
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  npm-checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bun check
        working-directory: npm
      - run: bun test
        working-directory: npm
  web-checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bun check
        working-directory: web
  web-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: bun run build:nuxt
        working-directory: web
